# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0f97548ec22d1b14ff4d9c28fa6bb64d0cbd7b2fb73416c7dfeb944ceedb0d6250d945af82186f321b41ac9b38763451c45aea051cc94111d5a4160c10c232b

test:
  secret_key_base: 5931073f3ba9e7a53df57e88e3e5f193f434ad14712802b66ba8dd1049fd6736e4640154fe652b30e1252a54046d770ff96ee6e27d01cf4ec495c74468bfeae8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
